### ISSUE TITLE
Getting ModuleNotFoundError: No module named 'imp' while running cfn-signal with python3.12

### ISSUE THREAD

**Issue by tgyanen** [aws-cloudformation/cloudformation-coverage-roadmap#2078]
### Name of the resource

Other

### Resource Name

cfn-signal

### Issue Description

`cfn-signal` does not work with python3.12

### Expected Behavior

`cfn-signal` should be able to send the signal succesfully

### Observed Behavior

Traceback (most recent call last):
  File "/usr/local/bin/cfn-signal", line 20, in <module>
    from cfnbootstrap.cfn_client import CloudFormationClient
  File "/usr/local/lib/python3.12/site-packages/cfnbootstrap/cfn_client.py", line 24, in <module>
    from cfnbootstrap import aws_client, util
  File "/usr/local/lib/python3.12/site-packages/cfnbootstrap/aws_client.py", line 23, in <module>
    from cfnbootstrap import util, public_constants
  File "/usr/local/lib/python3.12/site-packages/cfnbootstrap/util.py", line 17, in <module>
    from cfnbootstrap import endpoint_tool
  File "/usr/local/lib/python3.12/site-packages/cfnbootstrap/endpoint_tool.py", line 16, in <module>
    from cfnbootstrap.resources import documents
  File "/usr/local/lib/python3.12/site-packages/cfnbootstrap/resources/documents/__init__.py", line 17, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

### Test Cases

Install python3.12 on Amazon Linux 2023 or Amazon Linux 2.
Use python3.12 to run the `cfn-signal`

**Comment by p7-florian** [comment]
[Related discussion: 
](https://repost.aws/questions/QUYnAVjOxmTm-kF7uHYwlFtg/cfn-init-issue-on-ubuntu-24-04-ami)
